### ISSUE TITLE
[Fix] apply page 체크박스 워딩 수정

### ISSUE THREAD

**Issue by eonseok-jeon** [sopt-makers/sopt-recruiting-frontend#245]
### 🦎 TODO
- makers 인지 여부에 따라 동적 렌더링 하기

<img width="427" alt="스크린샷 2024-07-28 오후 3 48 20" src="https://github.com/user-attachments/assets/95215a64-8d36-4c02-ac2d-63ee19c17279">

**Comment by lydiacho** [comment]
![image](https://github.com/user-attachments/assets/09a9ff40-b731-459f-81ae-1bb33e9f1564)

개인정보 수집 동의 정책에 줄바꿈 발생하는 것도 같이 해결할게요!
