### ISSUE TITLE
[Fix] 사파리 - 이메일 내 타이머 위치 깨짐

### ISSUE THREAD

**Issue by lydiacho** [sopt-makers/sopt-recruiting-frontend#296]
### 🦎 TODO
사파리에서 적용되지 않는 css 들 발견 

> 좌 사파리, 우 크롬 

![image](https://github.com/user-attachments/assets/4e5c9ce3-5b38-492e-892e-e60be12979b7)

**Comment by eonseok-jeon** [comment]
옹? 이슈 파졌었구만유;
