### ISSUE TITLE
[Fix] 사파리 - 커서 포인터 및 Hover 효과 오류

### ISSUE THREAD

**Issue by lydiacho** [sopt-makers/sopt-recruiting-frontend#302]
### 🦎 TODO
사파리 브라우저에서 커서 포인터가 이상하게 적용되고 hover가 잘 안먹음 

https://github.com/user-attachments/assets/72a52ed9-9c34-483f-ae89-46445e86c804

**Comment by lydiacho** [comment]
@eonseok-jeon 
[관련 이슈가 이미 많이 올라와있었는데](https://apple.stackexchange.com/questions/361648/cusor-wont-react-to-hyperlinks-when-using-safari), 
결론은 **사파리가 무거우면** 이렇게 커서 및 hover 등 마우스 반응에 문제가 생긴다고 하네요 
위 논의에서 '포토샵을 꺼라' 라는 해결책이 있길래 
설마,,싶은 마음에 무거운 로컬 개발계 대신 배포본으로 다시 접속해서 보니까 hover 및 커서 모두 매우 잘 작동하네요..
이런 신기한 이슈도 있군요 
암튼 개발 단의 문제가 아닌 것이 확인되어 클로즈합니다 ~~

**Comment by eonseok-jeon** [comment]
@lydiacho 
근데 사파리 뿐 아니라 가끔 크롬도 마우스 호버 이상하게 작동하더라고요 끙,,
