### ISSUE TITLE
[Feat] 테스트 코드 초기 세팅

### ISSUE THREAD

**Issue by eonseok-jeon** [sopt-makers/sopt-recruiting-frontend#433]
@lydiacho 

테스트 코드를 추가하고자 하는데 어떻게 생각하시는지 의견이 궁금해요!

## 🪿 이유

1. 리소스 절약
지원서는 이슈가 발생하면 안 돼요 그렇기에 테스트가 꼼꼼하게 진행 되어야 합니다
하지만 이를 위해 매번 local에서 dev 띄워서 테스트(hot module reloading) 하는 건 리소스가 조금 드는 거 같아요
이를 코드 딴에서 간편하게 진행할 수 있게 하면 좋을 거 같아요

2. 지난 테스트의 반복 제거
`1. 리소스 절약`과 살짝 관련이 있는데요
새로운 기능을 개발하거나 기존 버그를 fix할 때마다 기존에 진행했었던 테스트(regression test)들을 다시 진행해줘야 해요
사실 지금껏 버그 수정하면서 고친 코드로 인해 원래 잘 작동되던 기능이 작동 안 하던 적이 몇 번 있었잖아요
그렇다고 매번 직접 테스트하기엔 너무나도 할 것들이 많고 시간이 너무 오래 걸려요
이를 테스트 코드를 통해 편하게 진행하면 좋을 거 같아요

3. 지원서의 변화가 많을까?
사실 테스트 코드를 짜기 어려운 이유 중 하나가 FE코드가 자주 바뀐다를 들 수가 있는데요
VOC나 이벤트 등에 의해 UI가 자주 추가/삭제 되면 그때마다 테스트 코드를 다시 짜줘야 하기에 조금 불편할 순 있어요
하지만 저희 지원서 서비스는 UI적으로 큰 변화가 없을 거라고 생각해요
그렇기에 이로 인한 추가 리소스는 적을 것이라 생각이 듭니다!

## 🪿 어떤 라이브러리를 사용할 것인가?
인기있는 라이브러리인 `Jest`와 `Vitest` 중 `Vitest`를 선택하기로 했어요

첫째, `Vitest`는 `Jest`보다 빨라요
약 4배 정도 빠르다고 합니다

둘째, `Vite`는 `Jest`보다 `Vitest`와 훨씬 잘 작동해요
다른 플랫폼에서는 `Jest`를 더 쉽게 사용할 수 있어요
실제로 `Next.js`는 `Jest`와 함께 사용하는 방법에 대한 [예제](https://nextjs.org/docs/app/building-your-application/testing/jest)가 공식문서에 있어요
하지만 vite.config.ts의 설정들을 별도의 설정 없이 바로 이용할 수 있는 등 `Vitest`가 `Vite`에 더 적합하다고 합니다

## 🪿 어디에 테스트 코드를 추가할 것인가?
- 지원하기 페이지
- 회원가입 페이지
- 비밀번호 변경 페이지
- (로그인 페이지)

위와 같이 input 요소 들이 들어간 곳에만 테스트 코드를 추가할 생각이에요
그 외의 부분들은 그렇게 복잡한 로직이 있는 것도 아니라서
hot module reloading를 통해 바로바로 테스트 하는게 오히려 더 빠를 거 같다는 생각입니다

이에 동의하시면 역할 나눠서 같이 해봐요~
다른 일이 많아 부담되거나 별로 좋은 아이디어 같지 않으면 괜찮으니까 편하게 얘기해 주세요 :)

## 참고자료
[Jest vs Vitest](https://saucelabs.com/resources/blog/vitest-vs-jest-comparison)
[테스트 코드 짜야하는가?](https://www.youtube.com/watch?v=Y7hQqBS2wK4)

**Comment by lydiacho** [comment]
좋은 아이디어인 것 같습니다! 

- 사소한 장애가 치명적일 수 있는 제품이다보니 저도 이번 스프린트 이후 테스팅 라이브러리를 도입하면 UX DX 모두 크게 개선될 수 있을 것 같다고 생각했어요! 아주아주 동의합니다 :) 
- ESM + TS + Vite 인 환경에서 Jest보다 Vites가 더 좋은 선택지인 것 같아요 
- 저도 이어지는 리팩토링으로 MSW 도입을 고민해보는 중이었는데, (이에 대해서는 더 근거 탄탄히 다져서 추후 따로 안건 던지겠습니다!) Vitest에서 서버 mocking 테스트로 MSW를 함께 사용하길 권장한다고 하네요. 둘의 합도 좋은 것 같아서 그런 의미에서도 Vitest 아주 좋은 선택인 것 같습니다 👍 

다만 도입이 급한 상황은 아니니, (저는) 도입 전에 우선 라브 좀더 제대로 파악할 시간이 주어지면 좋을 것 같아요!
내일 만나서 타임라인 잡아보고 역할 분담해봅시당 
좋은 제안 감사드려요 🚀🚀
