### ISSUE TITLE
[Feat] 대학교/학과 검색 api 연동

### ISSUE THREAD

**Issue by eonseok-jeon** [sopt-makers/sopt-recruiting-frontend#74]
### 🦎 TODO
- 대학교 검색 api 연동 [참고자료](https://www.career.go.kr/cnet/front/openapi/openApiSchoolCenter.do)
- 학과 검색 api 연동 [참고자료](https://www.career.go.kr/cnet/front/openapi/openApiMajorCenter.do)

**Comment by lydiacho** [comment]
@eonseok-jeon 
이거 관련해서 고민되는 부분이있어요! 

1. 대학교나 학과 데이터가 어어어ㅓ어어어어어어엄청 많아서 저희가 사용하는 SelectBox 형태로 제공하는건 말이 안되고, 검색이 가능한 Dialog를 만들어서 실시간 검색기능 구현이 필요할 것 같아요. 여기에 디자인, 개발 리소스가 추가적으로 필요해요

2. OpenAPI의 경우 브라우저에서 직접 요청하면 CORS가 터져요. 그래서 서버에게 해당 OpenAPI와 통신할 수 있는 중간다리 역할을 해주는 API를 뚫어달라고 해야 해요. 여기에 서버 리소스가 들어가요 

그래서 이걸 이번 스프린트에 가져가는게 맞을지, 추후로 빼는게 나을지 고민이에요. 
만약 그래도 이번에 가져가는게 맞다!고 생각하시면 해당 부분 디잔선생님들과 서버선상님께 바로 요청드리겠습니다!!

**Comment by eonseok-jeon** [comment]
@lydiacho 다음으로 넘겨도 좋을 거 같습니다~~
